import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, BookOpen, Briefcase, Bus, CaretDown, CaretRight, Car, ChartPieSlice, Check, CheckCircle, CircleNotch, FileArrowUp, ForkKnife, Gear, House, ListBullets, MagnifyingGlass, Notebook, Plus, Robot, ShoppingCart, SignOut, Sparkle, UserCircle, Users, Wallet } from "@phosphor-icons/react";
import { createBookSchema, createTransactionSchema, type SubscriptionPlan } from "@shared-ledger/shared";
import { Button, PageTitle, Panel } from "@shared-ledger/ui";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import { BrowserRouter } from "react-router-dom";
import { Area, AreaChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { api, money } from "./lib";

type Tx = { id: string; title: string; note: string; amount: number; type: "income" | "expense"; icon: "cart" | "meal" | "income" | "car"; member: string; date: string };
const transactions: Tx[] = [
  { id: "tx_market", title: "超市购物", note: "日常食材采购", amount: 158.6, type: "expense", icon: "cart", member: "张三", date: "06-20" },
  { id: "tx_dinner", title: "晚餐聚餐", note: "和朋友聚餐", amount: 236, type: "expense", icon: "meal", member: "李四", date: "06-19" },
  { id: "tx_salary", title: "工资收入", note: "6 月工资", amount: 8500, type: "income", icon: "income", member: "张三", date: "06-18" },
  { id: "tx_fuel", title: "加油费", note: "周末出行", amount: 320, type: "expense", icon: "car", member: "张三", date: "06-17" }
];
const transactionIcons = { cart: ShoppingCart, meal: ForkKnife, income: Briefcase, car: Car };
const nav = [{ to: "/books/book_home", label: "账本", Icon: House }, { to: "/records", label: "记录", Icon: ListBullets }, { to: "/imports", label: "导入", Icon: FileArrowUp }, { to: "/analysis", label: "分析", Icon: ChartPieSlice }, { to: "/settings", label: "我的", Icon: UserCircle }];
const actionLinks = [{ label: "成员管理", to: "/members", Icon: Users }, { label: "分类管理", to: "/settings/categories", Icon: ListBullets }, { label: "标签管理", to: "/settings/tags", Icon: Sparkle }, { label: "账户管理", to: "/settings/accounts", Icon: Wallet }, { label: "导出数据", to: "/settings/export", Icon: FileArrowUp }, { label: "隐私设置", to: "/settings/privacy", Icon: Gear }];

function usePlan() { const [plan, setPlan] = useState<SubscriptionPlan>(() => (localStorage.getItem("ledger-plan") as SubscriptionPlan) || "free"); const update = (next: SubscriptionPlan) => { localStorage.setItem("ledger-plan", next); setPlan(next); }; return { plan, update }; }
function AppFrame({ children, plan }: { children: React.ReactNode; plan: SubscriptionPlan }) { const location = useLocation(); const [drawer, setDrawer] = useState(false); const naked = ["/login", "/register"].includes(location.pathname); if (naked) return <main className="phone auth-shell">{children}</main>; return <main className="phone"><div className="content">{children}</div>{plan === "pro" && <><button className="ai-fab" aria-label="打开 AI 助手" onClick={() => setDrawer(true)}><Robot size={25} weight="fill" /></button>{drawer && <AiDrawer close={() => setDrawer(false)} />}</>}<nav className="bottom-nav">{nav.map(({ to, label, Icon }) => <Link key={to} to={to} className={location.pathname.startsWith(to) ? "active" : ""}><Icon size={23} weight={location.pathname.startsWith(to) ? "fill" : "regular"} /><span>{label}</span></Link>)}</nav></main>; }
function Back({ to }: { to?: string }) { const navigate = useNavigate(); return <button className="back" onClick={() => to ? navigate(to) : navigate(-1)} aria-label="返回"><ArrowLeft size={24} /></button>; }
function Page({ title, children, action, back = true }: { title: string; children?: React.ReactNode; action?: React.ReactNode; back?: boolean }) { return <><PageTitle title={title} action={action ?? (back ? <Back /> : undefined)} />{children}</>; }
function Transactions({ compact = false }: { compact?: boolean }) { const shown = compact ? transactions.slice(0, 3) : transactions; return <div className="transaction-list">{shown.map((tx) => { const Icon = transactionIcons[tx.icon]; return <Link to={`/records/${tx.id}`} className="transaction" key={tx.id}><span className="date">{compact ? tx.date : "2026年6月" + tx.date + "日"}</span><span className="category-icon"><Icon size={19} weight="fill" /></span><span className="transaction-copy"><strong>{tx.title}</strong><small>{tx.note} · {tx.member}</small></span><strong className={tx.type}>{tx.type === "income" ? "+" : "-"}{money(tx.amount)}</strong></Link>; })}</div> }

function Home() { return <><Page title="家庭账本" back={false} action={<Link className="icon-link" to="/books/book_home/settings"><Gear size={27} /></Link>} /><Panel className="summary"><div><span>2026年6月 <CaretDown size={16} /></span><small>切换月份</small></div><section><p>本月收入<b className="income">¥12,560.00</b></p><p>本月支出<b>¥8,230.00</b></p><p>结余<b className="income">¥4,330.00</b></p></section></Panel><Link className="pending-strip" to="/imports/pending"><CircleNotch size={22} weight="fill" /><b>待确认 <em>3</em></b><CaretRight size={22} /></Link><Panel><header className="section-header"><h2>最近记录</h2><Link to="/records">查看全部 <CaretRight /></Link></header><Transactions compact /></Panel><Link to="/records/new" className="primary-wide"><Plus size={24} weight="bold" />记一笔</Link></> }
function Books() { return <><Page title="我的账本" back={false} /><Panel className="book-hero"><BookOpen size={35} weight="fill" /><div><h2>家庭账本</h2><p>3 位成员 · 人民币</p></div><CaretRight /></Panel><Link className="add-row" to="/books/new"><Plus />新建账本</Link></> }
function BookForm() { const navigate = useNavigate(); const form = useForm({ resolver: zodResolver(createBookSchema), defaultValues: { name: "", currency: "CNY", note: "" } }); const submit = form.handleSubmit(async (value) => { await api("/books", { method: "POST", body: JSON.stringify(value) }).catch(() => undefined); navigate("/books/book_home"); }); return <><Page title="创建账本" /><form className="form" onSubmit={submit}><label>账本名称<input placeholder="例如：家庭账本" {...form.register("name")} /></label><p className="field-error">{form.formState.errors.name?.message}</p><label>默认货币<select {...form.register("currency")}><option value="CNY">人民币 CNY</option><option value="USD">美元 USD</option></select></label><label>备注<textarea placeholder="可选，说明这个账本的用途" {...form.register("note")} /></label><Button type="submit">创建账本</Button></form></> }
function Records() { const [filter, setFilter] = useState("全部"); return <><Page title="记录列表" action={<button className="icon-link"><MagnifyingGlass size={25} /></button>} back={false} /><input className="search" placeholder="搜索记录、分类、成员或备注" /><div className="chips">{["全部", "收入", "支出"].map((item) => <button className={filter === item ? "selected" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><Transactions /><Link to="/records/new" className="primary-wide"><Plus size={24} weight="bold" />记一笔</Link></> }
function TransactionForm() { const navigate = useNavigate(); const form = useForm({ resolver: zodResolver(createTransactionSchema), defaultValues: { type: "expense" as const, amount: undefined as unknown as number, occurredAt: new Date().toISOString().slice(0, 10), note: "", tagIds: [], items: [] } }); const submit = form.handleSubmit(async (value) => { await api("/books/book_home/transactions", { method: "POST", body: JSON.stringify(value) }).catch(() => undefined); navigate("/records"); }); return <><Page title="记一笔" /><form className="form transaction-form" onSubmit={submit}><div className="type-toggle"><button type="button" className={form.watch("type") === "expense" ? "selected" : ""} onClick={() => form.setValue("type", "expense")}>支出</button><button type="button" className={form.watch("type") === "income" ? "selected" : ""} onClick={() => form.setValue("type", "income")}>收入</button></div><label className="amount-field">金额<input type="number" step="0.01" inputMode="decimal" placeholder="0.00" {...form.register("amount", { valueAsNumber: true })} /></label><p className="field-error">{form.formState.errors.amount?.message}</p><label>分类<select><option>餐饮</option><option>交通</option><option>工资</option></select></label><label>日期<input type="date" {...form.register("occurredAt")} /></label><label>备注<textarea placeholder="写点说明…" {...form.register("note")} /></label><Link className="sub-action" to="/records/new/items">添加明细 <CaretRight /></Link><Button type="submit">保存记录</Button></form></> }
function RecordDetail() { const { id } = useParams(); const tx = transactions.find((item) => item.id === id) ?? transactions[0]; const Icon = transactionIcons[tx.icon]; return <><Page title="记录详情" action={<Link className="text-action" to={`/records/${tx.id}/edit`}>编辑</Link>} /><Panel className="detail-amount"><span><Icon size={31} weight="fill" /></span><h1 className={tx.type}>{tx.type === "income" ? "+" : "-"}{money(tx.amount)}</h1><p>{tx.title}</p></Panel><Panel className="detail-grid"><p><span>成员</span>{tx.member}</p><p><span>日期</span>2026年6月20日</p><p><span>账户</span>现金</p><p><span>标签</span>日常</p><p><span>备注</span>{tx.note}</p></Panel></> }
function Imports() { return <><Page title="导入记录" back={false} /><Panel className="upload-zone"><FileArrowUp size={42} weight="duotone" /><h2>导入账单或票据</h2><p>支持图片、PDF、CSV、Excel</p><button onClick={() => document.getElementById("file")?.click()}>选择文件</button><input id="file" type="file" hidden onChange={() => undefined} /></Panel><div className="tips"><h3>智能识别流程</h3><p>上传文件 → 提取文本/OCR → AI 整理 → 待确认入账</p></div><Link className="sub-action" to="/imports/pending">待确认记录 <b>3</b><CaretRight /></Link><Link className="sub-action" to="/imports/history">导入历史 <CaretRight /></Link></> }
function Pending() { const [confirmed, setConfirmed] = useState<string[]>([]); return <><Page title="待确认记录" action={<button className="text-action" onClick={() => setConfirmed(["a", "b"])}>全部确认</button>} /><Panel><p className="muted">智能识别结果，请确认后入账</p>{[{ id: "a", name: "超市购物", amount: 158.6, warning: "" }, { id: "b", name: "交通出行", amount: 32, warning: "疑似重复" }].map((item) => <div className="pending-row" key={item.id}><span className="category-icon">{item.id === "a" ? <ShoppingCart size={19} weight="fill" /> : <Bus size={19} weight="fill" />}</span><div><strong>{item.name}</strong><small>{item.warning || "识别置信度 94%"}</small></div><b>{money(item.amount)}</b><button disabled={confirmed.includes(item.id)} onClick={() => setConfirmed((old) => [...old, item.id])}>{confirmed.includes(item.id) ? <Check /> : "确认"}</button></div>)}</Panel></> }
function ImportHistory() { return <><Page title="导入历史" /><Panel><div className="history-row"><FileArrowUp size={25} /><div><strong>六月账单.csv</strong><small>2026-06-20 · 识别 12 条</small></div><span className="status success">已完成</span></div><div className="history-row"><FileArrowUp size={25} /><div><strong>购物小票.jpg</strong><small>2026-06-19 · 等待确认</small></div><span className="status">处理中</span></div></Panel></> }
function Analysis() { const trend = [{ d: "周一", value: 110 }, { d: "周二", value: 230 }, { d: "周三", value: 180 }, { d: "周四", value: 440 }, { d: "周五", value: 270 }, { d: "周六", value: 520 }]; const pie = [{ name: "餐饮", value: 36, color: "#ff681c" }, { name: "居住", value: 27, color: "#ffae75" }, { name: "交通", value: 20, color: "#315a9c" }, { name: "其他", value: 17, color: "#d8dee9" }]; return <><Page title="账本分析" back={false} /><div className="analysis-summary"><span><small>本月支出</small><b>¥8,230</b></span><span><small>较上月</small><b className="income">-8.2%</b></span></div><Panel><h2>支出趋势</h2><div className="chart"><ResponsiveContainer><AreaChart data={trend}><Tooltip /><Area type="monotone" dataKey="value" stroke="#ff681c" fill="#ffe9db" strokeWidth={3} /></AreaChart></ResponsiveContainer></div></Panel><Panel><h2>分类占比</h2><div className="pie-wrap"><ResponsiveContainer width="50%" height={180}><PieChart><Pie data={pie} dataKey="value" innerRadius={45} outerRadius={70}>{pie.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie></PieChart></ResponsiveContainer><ul>{pie.map((item) => <li key={item.name}><i style={{ background: item.color }} />{item.name}<b>{item.value}%</b></li>)}</ul></div></Panel></> }
function Members() { return <><Page title="成员管理" action={<Link className="text-action" to="/members/invite">邀请</Link>} /><Panel>{[{ name: "张三", role: "创建者" }, { name: "李四", role: "管理员" }, { name: "王五", role: "成员" }].map((member) => <Link to="/members/role" className="member-row" key={member.name}><span>{member.name.slice(0, 1)}</span><div><strong>{member.name}</strong><small>{member.role}</small></div><CaretRight /></Link>)}</Panel><Link className="sub-action" to="/invitations/received">我的邀请 <CaretRight /></Link><Link className="sub-action" to="/invitations/sent">已发邀请 <CaretRight /></Link></> }
function Invite() { const [sent, setSent] = useState(false); return <><Page title="邀请成员" /><div className="form"><label>邮箱或手机号<input placeholder="输入对方邮箱或手机号" /></label><label>成员角色<select><option>成员</option><option>管理员</option></select></label><Button onClick={() => setSent(true)}>{sent ? "已发送邀请" : "发送邀请"}</Button>{sent && <p className="success-note"><CheckCircle /> 邀请已发送，对方接受后将加入账本。</p>}</div></> }
function RoleEditor() { return <><Page title="成员权限" /><Panel className="role-intro"><span>李</span><h2>李四</h2><p>可查看与记录账本数据</p></Panel><div className="role-options">{["管理员", "成员"].map((role, index) => <label key={role}><input type="radio" name="role" defaultChecked={index === 0} />{role}<small>{index === 0 ? "可邀请成员、管理成员" : "可查看账本并记录"}</small></label>)}</div><Button>保存权限</Button></> }
function Settings({ plan, setPlan }: { plan: SubscriptionPlan; setPlan: (plan: SubscriptionPlan) => void }) { return <><Page title="我的" back={false} /><Panel className="profile"><span>张</span><div><h2>张三</h2><p>demo@ledger.local</p></div><Link to="/account"><CaretRight /></Link></Panel>{plan === "free" ? <Link to="/subscription" className="upgrade-banner"><Sparkle size={24} weight="fill" /><span><b>升级 Pro</b><small>开启 AI 账本助手</small></span><CaretRight /></Link> : <Link to="/ai" className="upgrade-banner"><Robot size={24} weight="fill" /><span><b>AI 助手已开启</b><small>随时分析你的账本</small></span><CaretRight /></Link>}<div className="settings-list">{actionLinks.map(({ label, to, Icon }) => <Link to={to} key={to}><Icon size={22} /><span>{label}</span><CaretRight /></Link>)}</div><button className="logout"><SignOut size={20} />退出登录</button><button className="demo-plan" onClick={() => setPlan(plan === "free" ? "pro" : "free")}>演示：切换为{plan === "free" ? " Pro" : "免费"}账户</button></> }
function SimpleSettings() { const location = useLocation(); const name = actionLinks.find((item) => location.pathname === item.to)?.label ?? "账本设置"; return <><Page title={name} /><Panel><h2>{name}</h2><p className="muted">这里已预留完整的管理入口。在 MVP 演示中，修改会在连接 API 后同步到账本成员。</p></Panel><div className="settings-list">{["新增项目", "排序管理", "保存更改"].map((item) => <button key={item}><span>{item}</span><CaretRight /></button>)}</div></> }
function Account() { return <><Page title="账号设置" /><Panel className="profile"><span>张</span><div><h2>张三</h2><p>demo@ledger.local</p></div></Panel><div className="settings-list">{["个人资料", "安全与登录", "通知设置", "语言与主题", "订阅与套餐"].map((item) => <button key={item}><span>{item}</span><CaretRight /></button>)}</div></> }
function Subscription({ setPlan }: { setPlan: (plan: SubscriptionPlan) => void }) { return <><Page title="订阅与套餐" /><Panel className="plan-card"><Sparkle size={33} weight="fill" /><h2>一起记 Pro</h2><p>让账本帮你发现每一笔钱的意义</p><ul><li><Check /> AI 账本助手</li><li><Check /> 智能分类与分析</li><li><Check /> 全局对话抽屉</li></ul><Button onClick={() => setPlan("pro")}>立即升级 ¥18/月</Button></Panel></> }
function Login({ register }: { register?: boolean }) { const navigate = useNavigate(); const form = useForm({ defaultValues: { email: "", password: "" } }); return <><div className="brand"><Notebook size={38} weight="fill" /><h1>一起记</h1><p>和重要的人，一起记下生活</p></div><form className="form auth-form" onSubmit={form.handleSubmit(() => navigate("/books/book_home"))}>{register && <label>昵称<input placeholder="怎么称呼你" /></label>}<label>邮箱<input type="email" placeholder="name@example.com" {...form.register("email")} /></label><label>密码<input type="password" placeholder="至少 8 位" {...form.register("password")} /></label>{register && <label className="check-label"><input type="checkbox" />我已阅读并同意服务协议</label>}<Button type="submit">{register ? "创建账号" : "登录"}</Button></form><p className="auth-switch">{register ? "已有账号？" : "还没有账号？"}<Link to={register ? "/login" : "/register"}>{register ? "去登录" : "注册"}</Link></p></> }
function AiDrawer({ close }: { close: () => void }) { const [message, setMessage] = useState(""); const [answer, setAnswer] = useState(""); return <aside className="ai-drawer"><header><div><Robot size={25} weight="fill" /><b>一起记 AI</b></div><button onClick={close}>×</button></header><div className="ai-content">{answer ? <p>{answer}</p> : <><Sparkle size={33} weight="fill" /><h2>今天想聊聊账本的什么？</h2><p>我可以分析趋势、解释图表或整理记录。</p></>}</div><form onSubmit={(event) => { event.preventDefault(); setAnswer(`关于“${message}”，本月餐饮支出占比最高，建议先确认 3 笔待入账记录。`); }}><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="问问你的账本…" /><button aria-label="发送"><CaretRight /></button></form></aside> }
function AiPage() { return <><Page title="AI 助手" /><div className="ai-page"><Robot size={42} weight="fill" /><h2>你好，张三</h2><p>我已准备好帮你理解这个账本。</p><div className="prompt-grid"><button>本月花在哪了？</button><button>帮我总结最近记录</button><button>有什么节省建议？</button></div></div></> }
export function App() { const { plan, update } = usePlan(); return <BrowserRouter><AppFrame plan={plan}><Routes><Route path="/" element={<Navigate to="/books/book_home" replace />} /><Route path="/login" element={<Login />} /><Route path="/register" element={<Login register />} /><Route path="/books" element={<Books />} /><Route path="/books/new" element={<BookForm />} /><Route path="/books/:id" element={<Home />} /><Route path="/books/:id/settings" element={<SimpleSettings />} /><Route path="/records" element={<Records />} /><Route path="/records/new" element={<TransactionForm />} /><Route path="/records/new/items" element={<SimpleSettings />} /><Route path="/records/:id" element={<RecordDetail />} /><Route path="/records/:id/edit" element={<TransactionForm />} /><Route path="/imports" element={<Imports />} /><Route path="/imports/pending" element={<Pending />} /><Route path="/imports/history" element={<ImportHistory />} /><Route path="/analysis" element={<Analysis />} /><Route path="/members" element={<Members />} /><Route path="/members/invite" element={<Invite />} /><Route path="/members/role" element={<RoleEditor />} /><Route path="/invitations/received" element={<SimpleSettings />} /><Route path="/invitations/sent" element={<SimpleSettings />} /><Route path="/settings" element={<Settings plan={plan} setPlan={update} />} /><Route path="/settings/:tab" element={<SimpleSettings />} /><Route path="/account" element={<Account />} /><Route path="/subscription" element={<Subscription setPlan={update} />} /><Route path="/ai" element={plan === "pro" ? <AiPage /> : <Navigate to="/subscription" replace />} /></Routes></AppFrame></BrowserRouter> }
